In [9]:
import numpy as np
arr = np.arange(1,21)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int32


In [14]:
np.random.seed(1)
arr=np.random.randint(10,size=(4,5))
print(arr)
arr.nbytes
arr.itemsize

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]]


4

In [20]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
arr=np.arange(1,7).reshape(2,3)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [4 5 6]]


In [22]:
np.random.seed(1)
arr=np.random.randint(10,size=(3,4))
print(arr)
print(arr[:2,:2])
print(arr[:,1::2])
print(arr[::-1])

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]]
[[8 5]
 [0 7]
 [9 4]]
[[6 9 2 4]
 [0 0 1 7]
 [5 8 9 5]]


In [23]:
np.random.seed(1)
arr=np.random.randint(10,size=(6,6))
print(arr)


[[5 8 9 5 0 0]
 [1 7 6 9 2 4]
 [5 2 4 2 4 7]
 [7 9 1 7 0 6]
 [9 9 7 6 9 1]
 [0 1 8 8 3 9]]
